services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: always
    ports:
      - "3002:80"  # Vue will be available on port 3000 inside Docker

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_backend
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"  # Go API will be available on port 8080

